version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
      - redis
    networks:
      - news_network
    environment:
      - DB_HOST=news_db
      - DB_PORT=3306
      - DB_DATABASE=laravel_news
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret

  nginx:
    image: nginx:alpine
    container_name: news_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - news_network

  db:
    image: mysql:8.0
    container_name: news_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_news
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - news_network
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:alpine
    container_name: news_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - news_network

networks:
  news_network:
    driver: bridge

volumes:
  dbdata:
    driver: local 